### PR TITLE
Add increase salary functionality in smart contract

### PR DESCRIPTION
**Pull request by RitwikSingh28**

### CODE REVIEW

**Comment by SrijanShovit** [comment]
Salary class add kr skte hain enum se ...depending upon class bhi promotion % depend krega

**Comment by SrijanShovit** [comment]
Time since last promotion bhi daal skte in some way

**Comment by RitwikSingh28** [comment]
What would be the use of 'Time since last promotion'? I can't think of its usage...

**Comment by SrijanShovit** [comment]
when did last my salary class change would help in changing class bcz % increase anually depends on that...class won't chnage every year..it changes every 5-10 yrs like so

**Comment by RitwikSingh28** [comment]
> when did last my salary class change would help in changing class bcz % increase anually depends on that...class won't chnage every year..it changes every 5-10 yrs like so

Okay, would try to integrate this as well in subsequent commits

**Comment by RitwikSingh28** [comment]
@SrijanShovit , please look at the implementation of the functionalities that we discussed in the above comments, and let me know if any changes should be made.. :+1:

**Comment by SrijanShovit** [comment]
good work

**Pull request merged**
